### PR TITLE
Multi user support and rewrite

### PR DESCRIPTION
**Pull request by AltF02**
We needed multi user support for the pewdiepie server, so I added the feature while also rewriting most of the code to be more object oriented and expandable

### CODE REVIEW

**Comment by AltF02** [comment]
I also made it more simple to configure with `config.yml` and I added a requirements.txt

**Review by psharma04 — APPROVED** [review]

**Comment by psharma04** [comment]
Successfully deployed this PR, requires major implementation changes so should be considered a major version.

**Comment by AltF02** [comment]
@fernandod1 bump 😄

**Comment by radulaa** [comment]
when 

`'edge_media_to_caption': {'edges': []},`

it will get this error

`return self.json['edge_media_to_caption']['edges'][0]['node']['text']`
`IndexError: list index out of range`

**Pull request closed without merging**
